name = "RecurrenceMicrostatesAnalysis"
uuid = "cb83a08b-85c6-4e94-91aa-4e946c7d4f0c"
version = "0.3.0"
repo = "https://github.com/DynamicsUFPR/RecurrenceMicrostatesAnalysis.jl"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distances = "0.10.12"
Statistics = "1.10.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
